src/Entity/Opening.php
<?php

namespace App\Entity;

use App\Repository\OpeningRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: OpeningRepository::class)]
class Opening
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 15)]
    private ?string $day = null;

    #[ORM\Column]
    #[Assert\GreaterThan(0)]
    private ?int $dayOrder = null;

    #[ORM\Column(length: 10)]
    private ?string $am_opening = null;

    #[ORM\Column(length: 10)]
    private ?string $am_closing = null;

    #[ORM\Column(length: 10)]
    private ?string $pm_opening = null;

    #[ORM\Column(length: 10)]
    private ?string $pm_closing = null;

    #[ORM\ManyToOne(inversedBy: 'openings')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Company $company = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDay(): ?string
    {
        return $this->day;
    }

    public function setDay(string $day): static
    {
        $this->day = $day;

        return $this;
    }

    public function getDayOrder(): ?int
    {
        return $this->dayOrder;
    }

    public function setDayOrder(int $dayOrder): static
    {
        $this->dayOrder = $dayOrder;

        return $this;
    }

    public function getAmOpening(): ?string
    {
        return $this->am_opening;
    }

    public function setAmOpening(string $am_opening): static
    {
        $this->am_opening = $am_opening;

        return $this;
    }

    public function getAmClosing(): ?string
    {
        return $this->am_closing;
    }

    public function setAmClosing(string $am_closing): static
    {
        $this->am_closing = $am_closing;

        return $this;
    }

    public function getPmOpening(): ?string
    {
        return $this->pm_opening;
    }

    public function setPmOpening(string $pm_opening): static
    {
        $this->pm_opening = $pm_opening;

        return $this;
    }

    public function getPmClosing(): ?string
    {
        return $this->pm_closing;
    }

    public function setPmClosing(string $pm_closing): static
    {
        $this->pm_closing = $pm_closing;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): static
    {
        $this->company = $company;

        return $this;
    }
}

src/Form/OpeningType.php
<?php

namespace App\Form;

use App\Entity\Company;
use App\Entity\Opening;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class OpeningType extends AbstractType
{
    
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $hours = [
            'Fermé' => 'Fermé',
            '6h' => '6h',
            '7h' => '7h',
            '8h' => '8h',
            '9h' => '9h',
            '10h' => '10h',
            '11h' => '11h',
            '12h' => '12h',
            '13h' => '13h',
            '14h' => '14h',
            '15h' => '15h',
            '16h' => '16h',
            '17h' => '17h',
            '18h' => '18h',
            '19h' => '19h',
            '20h' => '20h',
        ];
        $days = [
            'Lundi' => 'Lundi',
            'Mardi' => 'Mardi',
            'Mercredi' => 'Mercredi',
            'Jeudi' => 'Jeudi',
            'Vendredi' => 'Vendredi',
            'Samedi' => 'Samedi',
            'Dimanche' => 'Dimanche',
        ];
        $builder
            ->add('company', EntityType::class, [
                'class'=> Company::class,
                'choice_label'=> 'name',
                'label' => 'Société concernée',
            ])
            ->add('day', ChoiceType::class, [
                'choices'  => $days,
                'label' => 'Jour de la semaine',
                'label_attr' => [
                    'class' => 'form-label mb-3',
                ]
            ])
            ->add('am_opening', ChoiceType::class, [
            'choices'  => $hours,
            'attr' => [
                'class' => 'form-control',
                'minlength' => '1',
                'maxlength' => '255',
            ],
            'label' => 'Horaire d\'ouverture du matin',
        ])
            ->add('am_closing', ChoiceType::class, [
            'choices'  => $hours,
            'attr' => [
                'class' => 'form-control',
                'minlength' => '1',
                'maxlength' => '255',
            ],
            'label' => 'Horaire de fermeture du matin',
            ] )
            ->add('pm_opening', ChoiceType::class, [
            'choices'  => $hours,
            'attr' => [
                'class' => 'form-control',
                'minlength' => '1',
                'maxlength' => '255',
            ],
            'label' => 'Horaire d\'ouverture de l\'après-midi',
            ])
            ->add('pm_closing', ChoiceType::class, [
            'choices'  => $hours,
            'attr' => [
                'class' => 'form-control',
                'minlength' => '1',
                'maxlength' => '255',
            ],
            'label' => 'Horaire de fermeture de l\'après-midi',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Opening::class,
        ]);
    }
}

src/Controller/OpeningController.php
<?php

namespace App\Controller;

use App\Entity\Opening;
use App\Form\OpeningType;
use App\Repository\OpeningRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/horaires')]
class OpeningController extends AbstractController
{
    #[Route('/', name: 'app_opening_index', methods: ['GET'])]
    public function index(OpeningRepository $openingRepository): Response
    {
        return $this->render('opening/index.html.twig', [
            'openings' => $openingRepository->findAll(),
        ]);
    }


    #[Route('/nouveau', name: 'app_opening_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $opening = new Opening();
        $form = $this->createForm(OpeningType::class, $opening);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($opening);
            $entityManager->flush();

            return $this->redirectToRoute('app_opening_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('opening/new.html.twig', [
            'opening' => $opening,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_opening_show', methods: ['GET'])]
    public function show(Opening $opening): Response
    {
        return $this->render('opening/show.html.twig', [
            'opening' => $opening,
        ]);
    }

    #[Route('/{id}/modifier', name: 'app_opening_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Opening $opening, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(OpeningType::class, $opening);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_opening_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('opening/edit.html.twig', [
            'opening' => $opening,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_opening_delete', methods: ['POST'])]
    public function delete(Request $request, Opening $opening, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$opening->getId(), $request->request->get('_token'))) {
            $entityManager->remove($opening);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_opening_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/opening/_delete_form.html.twig
<form method="post" action="{{ path('app_opening_delete', {'id': opening.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ opening.id) }}">
    <button class="btn btn-dark mb-3">Supprimer</button>
</form>

templates/opening/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary mb-3">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/opening/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Garage V. PARROT - Modification Horaires{% endblock %}

{% block body %}
<div class="container d-flex">
    {% include "profile/profile/admin.html.twig" %}
    <div class="col-8">    
        <h1 class="mb-4">Modifier les horaires</h1>
    
        <a href="{{ path('app_opening_index') }}" class="btn btn-outline-secondary my-3">Retour à la liste</a>
            {{ form_errors(form) }}

            {{ form_start(form) }}
                {{ include('opening/_form.html.twig', {'button_label': 'Modifier'}) }}
                {{ include('opening/_delete_form.html.twig') }}
            {{ form_end(form) }}
    </div>
</div>
{% endblock %}

templates/opening/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Garage V. PARROT - Horaires{% endblock %}

{% block body %}
<div class="container d-flex">
{% include "profile/profile/admin.html.twig" %}
    <div class="col-8">
        <h1 class="mb-4">Gestion des horaires d'ouverture</h1>

        <a href="{{ path('app_opening_new') }}" class="btn btn-outline-secondary">Ajouter un nouvel horaire</a>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Jour de la semaine</th>
                    <th>Ouverture - Matin</th>
                    <th>Fermeture - Matin</th>
                    <th>Ouverture - Après-midi</th>
                    <th>Fermeture - Après-midi</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
            {% for opening in openings %}
                <tr>
                    <td>{{ opening.day }}</td>

                    <td>{% if opening.amOpening == 'Fermé' %}Fermé {% else %} {{opening.amOpening}}
                        {% endif %}
                    </td>
                    <td>{% if opening.amClosing == 'Fermé' %}Fermé {% else %} {{opening.amClosing}}
                        {% endif %}
                    </td>
                    <td>{% if opening.pmOpening == 'Fermé' %}Fermé {% else %} {{opening.pmOpening}}
                        {% endif %}
                    </td>
                    <td>{% if opening.pmClosing == 'Fermé' %}Fermé {% else %} {{opening.pmClosing}}
                        {% endif %}
                    </td>

                
                    <td>
                        <a href="{{ path('app_opening_edit', {'id': opening.id}) }}">Modifier</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="8">Il n'y a aucun horaire défini actuellement</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/opening/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Garage V. PARROT - Nouvel Horaire{% endblock %}

{% block body %}
<div class="container d-flex justify-content-center">
    <h1 class="my-5">Créer une annonce </h1>
</div>
<div class="container d-flex justify-content-center">
    <div class="col-8">
        {{ form_errors(form) }}

        {{ form_start(form) }}
                {{ include('opening/_form.html.twig', {'button_label': 'Créer l\'horaire'}) }}
                <a href="{{ path('app_opening_index') }}" class="btn btn-dark my-3">Retour à la liste</a>        {{ form_end(form) }}
        {{ form_end(form) }}
    </div>
</div>
{% endblock %}

templates/opening/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Opening{% endblock %}

{% block body %}
    <h1>Opening</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ opening.id }}</td>
            </tr>
            <tr>
                <th>Day</th>
                <td>{{ opening.day }}</td>
            </tr>
            <tr>
                <th>Am_opening</th>
                <td>{{ opening.amOpening }}</td>
            </tr>
            <tr>
                <th>Am_closing</th>
                <td>{{ opening.amClosing }}</td>
            </tr>
            <tr>
                <th>Pm_opening</th>
                <td>{{ opening.pmOpening }}</td>
            </tr>
            <tr>
                <th>Pm_closing</th>
                <td>{{ opening.pmClosing }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_opening_index') }}">back to list</a>

    <a href="{{ path('app_opening_edit', {'id': opening.id}) }}">edit</a>

    {{ include('opening/_delete_form.html.twig') }}
{% endblock %}